workflows:
  default-workflow:
    name: Default workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PACKAGE_NAME: "com.kodman.news"
        GOOGLE_PLAY_TRACK: "alpha"
    scripts:
      - name: Flutter build ipa
        script: |
            flutter build ipa --debug
    # Add scripts here
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - kodman.dev@gmail.com